kind: Deployment
apiVersion: apps/v1
metadata:
  name: sample-view
  labels:
    app: dev-sample-view
spec:
  selector:
    matchLabels:
      deployment: dev-sample-view
  template:
    metadata:
      labels:
        deployment: dev-sample-view
        app: dev-sample-view
    spec:
      containers:
        - name: sample-view
          image: image-registry.openshift-image-registry.svc:5000/jiadchen-dev/sample-view:791b979d17375fb1badbe7ac09459f17ec93a0a1
          env:
            - name: API_BASE_URL
              value: https://dev-sample-app-jiadchen-dev.apps.sandbox-m2.ll9k.p1.openshiftapps.com
